create sequence ERROR_LOG_SEQ;

CREATE TABLE ERROR_LOG
(
  ERROR_LOG_ID     INTEGER                      NOT NULL,
  STACKTRACE       VARCHAR2(4000 BYTE)          NOT NULL,
  MODULE           VARCHAR2(200 BYTE)           NOT NULL,
  ERROR_TYPE       VARCHAR2(20 BYTE)            NOT NULL,
  CREATED_BY       VARCHAR2(150 BYTE)           NOT NULL,
  CREATED_ON       DATE                         NOT NULL,
  LAST_UPDATED_BY  VARCHAR2(150 BYTE)           NOT NULL,
  LAST_UPDATED_ON  DATE                         NOT NULL
);


CREATE OR REPLACE TRIGGER ERROR_LOG_BI
   BEFORE INSERT
   ON ERROR_LOG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN
   IF :New.ERROR_LOG_ID IS NULL
   THEN
      SELECT ERROR_LOG_SEQ.NEXTVAL INTO :NEW.ERROR_LOG_ID FROM DUAL;
   END IF;

   :new.created_by := NVL (v ('APP_USER'), USER);
   :new.created_on := SYSDATE;
   :new.LAST_UPDATED_BY := NVL (v ('APP_USER'), USER);
   :new.LAST_UPDATED_ON := SYSDATE;
END;
/


CREATE OR REPLACE TRIGGER ERROR_LOG_BU
   BEFORE UPDATE
   ON ERROR_LOG
   FOR EACH ROW
BEGIN
   :new.LAST_UPDATED_BY := NVL (v ('APP_USER'), USER);
   :new.LAST_UPDATED_ON := SYSDATE;
END;
/
